### ISSUE TITLE
Remove older connector versions when installing connector

### ISSUE THREAD

**Issue by ThisaruGuruge** [wso2-ballerina/module-kafka#40]
**Description:**
> Currently when Kafka Connector is installing, we only copy the relevant jars to the ballerina home. But When an older (or a newer) version of Kafka Connector jar is available already, it will not be removed. This may lead to errors when running a ballerina program with Kafka module. 

Hence when the user is installing Kafka Connector using the installation scripts, script should look for other Kafka Connector jars, and remove them first.

**Related Issues:**
> #38

**Comment by kalaiyarasiganeshalingam** [comment]
Fixed in #41
