### ISSUE TITLE
No detailed guide to try the samples

### ISSUE THREAD

**Issue by Shakila** [wso2-ballerina/module-kafka#43]
**Description:**
We have the Kafka samples [1]. But we don't have a guide/doc with configuration steps to try these samples.
[1] https://github.com/wso2-ballerina/module-kafka/tree/master/samples/ballerina-by-example/examples

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ThisaruGuruge** [comment]
These examples are following the same way that the [ballerina by example (BBE)](https://ballerina.io/learn/by-example/) follows. These tests contain a `.description` file, and a `.out` file, as the BBEs.

But as the Kafka is residing outside of the Ballerina lang currently, hence they don't help much. But as we are going to move the Kafka module inside the ballerina repository, this issue will be resolved.

**Comment by wggihan** [comment]
Kafka module now shipped with by default and BBE is available for this.
